config/routes.rb
Rails.application.routes.draw do
  root 'returns#index'

  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  resources :manufacturers
  resources :brands
  resources :returns

  get '/reset_password' => 'admin#reset'
  get '/collection' => 'manufacturers#collection'
  get '/filter' => 'returns#filter'
  post '/import' => 'returns#import'
end

app/models/return.rb
class Return < ActiveRecord::Base
  belongs_to :brand
  belongs_to :manufacturer

  validates :auth_number, :return_date, :brand_id, :manufacturer_id, :frame_count, presence: true

  validates :frame_count, numericality: { greater_than_or_equal_to: 1 }

  def credited?
    self.credit_memo_number != "" && self.credit_memo_number
  end

  def days_pending
    (Date.today - self.return_date).to_i
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ["Manufacturer", "Brand", "Frame Count", "RA Number", "RA Date", "CM Number", "CM Date", "Notes"]
      all.order(:return_date).each do |entry|
        csv << [
          entry.manufacturer.name,
          entry.brand.name,
          entry.frame_count,
          entry.auth_number,
          entry.return_date.try(:strftime, '%m-%d-%Y'),
          entry.credit_memo_number,
          entry.credit_date.try(:strftime, '%m-%d-%Y'),
          entry.comments
        ]
      end
    end
  end

end

app/controllers/returns_controller.rb
require 'csv'

class ReturnsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @manufacturers = Manufacturer.all.order(:name)
    @brands = Brand.all.order(:name)
    @returns = Return.all.order(:return_date)
    @pending = Return.where("credit_memo_number = '' OR credit_memo_number IS NULL").order(:return_date)
    respond_to do |format|
      format.html
      format.pdf do
        render  pdf: "returns"
      end
      format.xls { send_data @returns.to_csv(col_sep: "\t") }
    end
  end

  def show
    @return = Return.find(params[:id])
    if request.xhr?
      render 'show', layout: false
    end
  end

  def new
    @return = Return.new
  end

  def edit
    @return = Return.find(params[:id])
    @brands = Manufacturer.find(@return.manufacturer_id).brands
  end

  def create
    @return = Return.new(return_params)

    if @return.save
      flash[:notice] = "Return successfully created"
      redirect_to returns_path
    else
      @brands = Manufacturer.find(params["return"]["manufacturer_id"]).brands if params["return"]["manufacturer_id"] != ""
      render 'new'
    end
  end

  def update
    @return = Return.find(params[:id])

    if @return.update(return_params)
      flash[:notice] = "Return successfully updated"
      redirect_to returns_path
    else
      @brands = Manufacturer.find(params["return"]["manufacturer_id"]).brands if params["return"]["manufacturer_id"] != ""
      render 'edit'
    end
  end

  def destroy
    @return = Return.find(params[:id])
    @return.destroy
    flash[:notice] = "Return successfully deleted"
    redirect_to returns_path
  end

  def filter
    if params[:manufacturer]
      manufacturer = Manufacturer.find_by(name: params[:manufacturer])
      @returns = Return.where(manufacturer_id: manufacturer.id)
    elsif params[:brand]
      brand = Brand.find_by(name: params[:brand])
      @returns = Return.where(brand_id: brand.id)
    end

    render '_table', layout: false, locals: {returns: @returns, table_class: 'filtered-table'}
  end

  def import
    number_of_returns = 0

    CSV.foreach(params[:file].path, headers: true) do |row|
      return_hash = row.to_hash

      manufacturer = Manufacturer.find_or_create_by(name: return_hash["Manufacturer"])
      brand = Brand.find_or_create_by(name: return_hash["Brand"])

      manufacturer.brands << brand unless manufacturer.brands.exists?(brand.id)

      return_ar = Return.new(
        auth_number: return_hash["RA Number"],
        return_date: Date.strptime(return_hash["RA Date"], '%m-%d-%Y').to_s,
        credit_date: return_hash["CM Date"] && Date.strptime(return_hash["CM Date"], '%m-%d-%Y').to_s,
        credit_memo_number: return_hash["CM Number"],
        brand_id: brand.id,
        manufacturer_id: manufacturer.id,
        frame_count: return_hash["Frame Count"],
        comments: return_hash["Notes"]
      )

      number_of_returns += 1 if return_ar.save
    end

    flash[:notice] = "#{number_of_returns} returns successfully imported"

    redirect_to returns_path
  end

  private

  def return_params
    params.require(:return).permit(:auth_number, :return_date, :credit_date, :credit_memo_number, :brand_id, :manufacturer_id, :frame_count, :comments)
  end
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/views/returns/_brand_select.html.erb
<%= label :return, :brand, '*Brand' %>
<%= collection_select(:return, :brand_id, @brands + [Brand.new(name: 'Create New...')], :id, :name, {prompt: true}, {class: "brand-select-menu"}) %>

app/views/returns/_form.html.erb
<%= render 'layouts/errors', object: @return %>

<div class="col-md-offset-4 col-sm-offset-3">
  <p>* = required</p>

  <div class="form-container return-form">
    <%= form_for @return do |f| %>
      <div class="form-group manufacturer-select">
        <%= render 'manufacturer_select' %>
      </div>
      <% if @return.brand_id %>
        <div class="form-group brand-select">
          <%= render 'brand_select', brands: @brands %>
        </div>
      <% else %>
        <div class="form-group brand-select">
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :frame_count, '*Frame Count' %>
        <%= f.number_field :frame_count, step: 1 %>
      </div>
      <div class="form-group">
        <%= f.label :auth_number, '*Return authorization number' %>
        <%= f.text_field :auth_number %>
      </div>
      <div class="form-group">
        <%= f.label :return_date, '*Return authorization date' %>
        <%= f.date_field :return_date %>
      </div>
      <div class="form-group">
        <%= f.label :credit_memo_number %>
        <%= f.text_field :credit_memo_number %>
      </div>
      <div class="form-group">
        <%= f.label :credit_date %>
        <%= f.date_field :credit_date %>
      </div>
      <div class="form-group">
        <%= f.label :comments %></br>
        <%= f.text_area :comments, cols: 55, rows: 3 %>
      </div>

      <%= f.submit "Submit", class: "btn btn-primary-outline" %>
      <%= link_to "Back", root_path, class: "btn btn-primary-outline" %>
    <% end %>
  </div>
</div>

app/views/returns/_manufacturer_select.html.erb
<%= label :return, :manufacturer, '*Manufacturer' %>
<%= collection_select(:return, :manufacturer_id, Manufacturer.all.order(:name) + [Manufacturer.new(name: 'Create New...')], :id, :name, {prompt: true}, {class: "manufacturer-select-menu"}) %>

app/views/returns/_table.html.erb
<div class="table-full">
  <div class="table-responsive">
    <table class="table tablesorter <%= table_class %>" data-sort="table">
      <thead>
        <tr>
          <th>Manufacturer</th>
          <th>Brand</th>
          <th>Frame Count</th>
          <th>RA Number</th>
          <th>RA Date</th>
          <th>CM Number</th>
          <th>CM Date</th>
        </tr>
      </thead>
      <tbody>
        <% returns.each do |data| %>
          <% if data.comments == "" || !data.comments %>
            <tr>
          <% else %>
            <tr class="commented">
          <% end %>
            <td><%= data.manufacturer.name %></td>
            <td><%= data.brand.name %></td>
            <td><%= data.frame_count %></td>
            <td><%= link_to data.auth_number, return_path(data), class: "return-details" %></td>
            <td><%= data.return_date.strftime("%m-%d-%Y") %></td>
            <td><%= data.credit_memo_number %></td>
            <% if data.credited? && data.credit_date %>
              <td><%= data.credit_date.strftime("%m-%d-%Y") %></td>
            <% else %>
              <td><%= data.credit_date %></td>
            <% end %>
            <td>
              <%= link_to edit_return_path(data) do %>
                <span class="icon icon-pencil"></span>
              <% end %>
            </td>
            <td>
              <%= link_to return_path(data), method: :delete, data: {confirm: "Are you sure?"} do %>
                <span class="icon icon-trash"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/returns/edit.html.erb
<div class="hr-divider m-t m-b-md">
  <h3 class="hr-divider-content">Update Return</h3>
</div>
<%= render 'form' %>

app/views/returns/index.html.erb
<div class="dashhead">
  <div class="dashhead-titles">
    <h3 class="dashhead-title">Returns Overview</h3>
  </div>
  <div class="pull-right">
    <%= link_to raw("<span class='icon icon-circle-with-plus'></span> New Return"), new_return_path, class: "btn btn-primary-outline" %>
    <%= link_to 'Export PDF', returns_path(:format => :pdf), {target: "_blank", class: "btn btn-primary-outline"} %>
  </div>
</div>

<div class="flex justify-flex-end hide">
  <%= form_tag import_path, multipart: true, class: 'flex flex-row' do %>
    <%= submit_tag('Import', class: 'btn btn-primary-outline') %>
    <%= file_field_tag :file, class: 'ml-10' %>
  <% end %>
</div>

<div class="pull-right">
  <%= link_to "Export to Excel", returns_path(format: "xls"), class: "btn btn-primary-outline" %>
</div>


<div class="pull-right">
  <%= link_to raw("<span class='icon icon-tools'></span> Manage Manufacturers & Brands"), manufacturers_path, class: "btn btn-primary-outline" %>
</div>

<select class="custom-select custom-select-sm m-filter">
  <option>Filter By Manufacturer</option>
  <%= @manufacturers.each do |manufacturer| %>
    <option><%= manufacturer.name %></option>
  <% end %>
</select>

<select class="custom-select custom-select-sm b-filter">
  <option>Filter By Brand</option>
  <%= @brands.each do |brand| %>
    <option><%= brand.name %></option>
  <% end %>
</select>

<%= render 'layouts/modal' %>

<ul class="nav nav-bordered m-b-0 return-tabs" role="tablist">
  <li role="presentation">
    <a href="#all" role="tab" data-toggle="tab" aria-controls="all">All Returns</a>
  </li>
  <li class="active" role="presentation">
    <a href="#pending" role="tab" data-toggle="tab" aria-controls="pending">Pending Returns</a>
  </li>
  <li role="presentation">
    <a href="#filter" role="tab" data-toggle="tab" aria-controls="filter">Filtered Returns</a>
  </li>
</ul>

<hr class="m-t-0 m-b-0">

<div class="tab-content">
  <div role="tabpanel" class="tab-pane" id="filter">
  </div>
  <div role="tabpanel" class="tab-pane" id="all">
    <%= render 'table', returns: @returns, table_class: 'all-table' %>
    <div id="all-pager" class="pager">
      <form>
        <span class="prev icon icon-controller-fast-backward"/></span>
        <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
        <span class="next icon icon-controller-fast-forward"/></span>
      </form>
    </div>
  </div>
  <div role="tabpanel" class="tab-pane active" id="pending">
    <%= render 'table', returns: @pending, table_class: 'pending-table' %>
    <div id="pending-pager" class="pager flex flex-row justify-flex-center">
      <form>
        <span class="prev icon icon-controller-fast-backward"/></span>
        <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
        <span class="next icon icon-controller-fast-forward"/></span>
      </form>
      <select class="gotoPage ml-10" title="Select page number">
    </div>
  </div>
</div>

app/views/returns/index.pdf.erb
<%= wicked_pdf_stylesheet_link_tag "pdf" %>
<h2>Pending Returns on <%= Time.now.strftime("%B %d, %Y") %></h2>
<table class="pdf-table">
  <thead>
    <tr>
      <th>Manufacturer</th>
      <th>Brand</th>
      <th>Count</th>
      <th>RA #</th>
      <th>Date</th>
      <th>Comments</th>
    </tr>
  </thead>
  <tbody>
    <% @pending.each do |data| %>
        <td><%= data.manufacturer.name %></td>
        <td><%= data.brand.name %></td>
        <td><%= data.frame_count %></td>
        <td><%= data.auth_number %></td>
        <td class="pdf-date"><%= data.return_date.strftime("%m-%d-%Y") %></td>
        <td class="pdf-comments"><%= data.comments %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/returns/new.html.erb
<div class="hr-divider">
  <h3 class="hr-divider-content">New Return</h3>
</div>
<%= render 'form' %>

<%= render 'layouts/modal', layout: false %>

app/views/returns/show.html.erb
<div class="text-center">
  <h4><%= @return.return_date %></h4>
  <h2>RA #<%= @return.auth_number %></h2>

  <h3><%= @return.manufacturer.name %> | <%= @return.brand.name %></h3>
  <p><%= @return.frame_count %> Frame(s)</p>

  <% if @return.credited? %>
    <div class="green">
      <p>Credited on <%= @return.credit_date %> - Credit Memo #<%= @return.credit_memo_number %></p>
    </div>
  <% else %>
    <div class="red">
      <p>No credit yet: <%= @return.days_pending %> days since authorization</p>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <% if @return.comments != "" && @return.comments %>
      <div class="hr-divider m-t m-b">
        <h3 class="hr-divider-content hr-divider-heading">Notes</h3>
      </div>
      <p class="text-center"><%= @return.comments %></p>
    <% end %>
  </div>
</div>