config/routes.rb
Rails.application.routes.draw do
  root 'returns#index'

  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  resources :manufacturers
  resources :brands
  resources :returns

  get '/reset_password' => 'admin#reset'
  get '/collection' => 'manufacturers#collection'
  get '/filter' => 'returns#filter'
  post '/import' => 'returns#import'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_and_belongs_to_many :manufacturers
  has_many :returns

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @brands = Brand.all.order(:name)
  end

  def new
    @brand = Brand.new
    if request.xhr?
      render '_form', layout: false
    end
  end

  def edit
    @brand = Brand.find(params[:id])
    if request.xhr?
      render '_form', layout: false
    end
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      if request.xhr?
        manufacturer = Manufacturer.find_by(name: params[:manufacturer])
        @brand.manufacturers << manufacturer
        @brands = manufacturer.brands.sort_by {|brand| brand.name}
        render 'returns/_brand_select', layout: false
      else
        flash[:notice] = "Brand successfully added"
        redirect_to returns_path
      end
    else
      if request.xhr?
        manufacturer = Manufacturer.find_by(name: params[:manufacturer])
        if @existing_brand = Brand.find_by(name: params["brand"]["name"])
          if @existing_brand.manufacturers.include?(manufacturer)
            render json: @brand.errors, status: :unprocessable_entity
          else
            @existing_brand.manufacturers << manufacturer
            @brands = manufacturer.brands.sort_by {|brand| brand.name}
            render 'returns/_brand_select', layout: false
          end
        else
          render json: @brand.errors, status: :unprocessable_entity
        end
      else
        render 'new'
      end
    end
  end

  def update
    @brand = Brand.find(params[:id])

    if @brand.update(brand_params)
      if request.xhr?
        manufacturer = Manufacturer.find_by(name: params[:manufacturer])
        @brands = manufacturer.brands.sort_by {|brand| brand.name}
        render '_list', layout: false
      else
        flash[:notice] = "Brand successfully updated"
        redirect_to brands_path
      end
    else
      if request.xhr?
        render json: @brand.errors, status: :unprocessable_entity
      else
        render 'edit'
      end
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    if request.xhr?
      manufacturer = Manufacturer.find_by(name: params[:manufacturer])

      if @brand.manufacturers.count > 1
        manufacturer.brands.delete(@brand)
        returns = Return.where(brand_id: @brand.id, manufacturer_id: manufacturer.id)
        returns.each { |data| data.destroy }
      else
        returns = Return.where(brand_id: @brand.id)
        returns.each { |data| data.destroy }
        @brand.destroy
      end

      @brands = manufacturer.brands.sort_by {|brand| brand.name}
      render '_list', layout: false
    else
      @brand.destroy
      redirect_to brands_path
    end
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<div class="brand-errors">
  <%= render 'layouts/errors', object: @brand %>
</div>

<div class="form-container text-center brand-form">
  <%= form_for @brand do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary-outline" %>
  <% end %>
</div>

app/views/brands/_list.html.erb
<div class="table-full col-md-5 col-sm-5 col-xs-6">
  <div class="table-responsive">
    <table class="table tablesorter" data-sort="b-table">
      <thead>
        <tr>
          <th>Brands</th>
        </tr>
      </thead>
      <tbody>
        <% @brands.each do |brand| %>
          <tr class="b-row">
            <td class="b-nabe"><%= brand.name %></td>
            <td class="edit-m">
              <%= link_to edit_brand_path(brand), remote: true, class: "edit-brand" do %>
                <span class="icon icon-pencil"></span>
              <% end %>
            </td>
            <td>
              <%= link_to brand_path(brand), class: "delete-brand", method: :delete, data: {confirm: "Are you sure? This will also delete all associated returns."} do %>
                <span class="icon icon-trash"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/brands/edit.html.erb
<div class="hr-divider">
  <h3 class="hr-divider-content">Edit Brand</h3>
</div>

<%= render 'form' %>

app/views/brands/index.html.erb
<div class="hr-divider">
  <h3 class="hr-divider-content">Manage Brands</h3>
</div>

<div class="list-container">
  <div class="brand-list">
    <%= render 'list' %>
  </div>
</div>

<%= render 'layouts/modal', layout: false %>

app/views/brands/new.html.erb
<div class="hr-divider">
  <h3 class="hr-divider-content">New Brand</h3>
</div>

<%= render 'form' %>