config/routes.rb
Rails.application.routes.draw do
  root 'returns#index'

  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  resources :manufacturers
  resources :brands
  resources :returns

  get '/reset_password' => 'admin#reset'
  get '/collection' => 'manufacturers#collection'
  get '/filter' => 'returns#filter'
  post '/import' => 'returns#import'
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_and_belongs_to_many :brands
  has_many :returns, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :authenticate_admin!

  def collection
    manufacturer = Manufacturer.find_by(name: params[:name])
    @brands = manufacturer.brands.sort_by {|brand| brand.name}
    render 'returns/_brand_select', layout: false
  end

  def index
    @manufacturers = Manufacturer.all.order(:name)
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
    @brands = @manufacturer.brands.sort_by {|brand| brand.name}

    if request.xhr?
      render 'brands/_list', layout: false
    end
  end

  def new
    @manufacturer = Manufacturer.new
    if request.xhr?
      render '_form', layout: false
    end
  end

  def edit
    @manufacturer = Manufacturer.find(params[:id])
    if request.xhr?
      render '_form', layout: false
    end
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      if request.xhr?
        render 'returns/_manufacturer_select', layout: false
      else
        flash[:notice] = "Manufacturer successfully added"
        redirect_to returns_path
      end
    else
      if request.xhr?
        render json: @manufacturer.errors, status: :unprocessable_entity
      else
        render 'new'
      end
    end
  end

  def update
    @manufacturer = Manufacturer.find(params[:id])

    if @manufacturer.update(manufacturer_params)
      if request.xhr?
        @manufacturers = Manufacturer.all.order(:name)
        render '_list', layout: false
      else
        flash[:notice] = "Manufacturer successfully updated"
        redirect_to manufacturers_path
      end
    else
      if request.xhr?
        render json: @manufacturer.errors, status: :unprocessable_entity
      else
        render 'edit'
      end
    end
  end

  def destroy
    @manufacturer = Manufacturer.find(params[:id])
    brands = @manufacturer.brands
    brands.first.destroy if brands.count == 1

    @manufacturer.destroy
    if request.xhr?
      @manufacturers = Manufacturer.all.order(:name)
      render '_list', layout: false
    else
      redirect_to manufacturers_path
    end
  end


  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name)
  end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/manufacturers/_form.html.erb
<div class="manufacturer-errors">
  <%= render 'layouts/errors', object: @manufacturer %>
</div>

<div class="form-container text-center manufacturer-form">
  <%= form_for @manufacturer do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary-outline" %>
  <% end %>
</div>

app/views/manufacturers/_list.html.erb
<div class="table-full col-md-offset-1 col-md-5 col-sm-offset-1 col-sm-5 col-xs-6">
  <div class="table-responsive">
    <table class="table tablesorter" data-sort="m-table">
      <thead>
        <tr>
          <th>Manufacturers</th>
        </tr>
      </thead>
      <tbody>
        <% @manufacturers.each do |manufacturer| %>
          <tr class="m-row">
            <td class="m-name"><%= link_to manufacturer.name, manufacturer_path(manufacturer) %></td>
            <td class="edit-m">
              <%= link_to edit_manufacturer_path(manufacturer), remote: true, class: "edit-manufacturer" do %>
                <span class="icon icon-pencil"></span>
              <% end %>
            </td>
            <td>
              <%= link_to manufacturer_path(manufacturer), remote: true, class: "delete-manufacturer", method: :delete, data: {confirm: "Are you sure? This will also delete all associated returns."} do %>
                <span class="icon icon-trash"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/manufacturers/edit.html.erb
<div class="hr-divider">
  <h3 class="hr-divider-content">Edit Manufacturer</h3>
</div>

<%= render 'form' %>

app/views/manufacturers/index.html.erb
<div class="hr-divider">
  <h3 class="hr-divider-content">Manage Manufacturers & Brands</h3>
</div>

<div class="list-container row">
  <div class="manufacturer-list">
    <%= render 'list' %>
  </div>

  <div class="brand-list">
  </div>
</div>

<div class="row">
  <%= link_to "Back", root_path, class: "btn btn-primary-outline" %>
</div>

<%= render 'layouts/modal', layout: false %>

app/views/manufacturers/new.html.erb
<div class="hr-divider">
  <h3 class="hr-divider-content">New Manufacturer</h3>
</div>

<%= render 'form' %>

app/views/manufacturers/show.html.erb
<h3><%= @manufacturer.name %>'s Brands</h3>

<%= render 'brands/list' %>