config/routes.rb
Rails.application.routes.draw do
  root 'returns#index'

  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  resources :manufacturers
  resources :brands
  resources :returns

  get '/reset_password' => 'admin#reset'
  get '/collection' => 'manufacturers#collection'
  get '/filter' => 'returns#filter'
  post '/import' => 'returns#import'
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% elsif alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_modal.html.erb
<div class="modal">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="nav navbar-fixed-top navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <strong class="main-header">Eye City Optometry</strong>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="text-muted">Returns <b class="caret"></b></span>
                    </a>
                    <ul class="dropdown-menu">
                        <% if current_admin %>
                            <li>
                                <%= link_to 'Home', root_path %>
                            </li>
                            <li>
                                <%= link_to "My Account", edit_admin_registration_path %>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <%= link_to "Logout", destroy_admin_session_path, method: :delete %>
                            </li>
                        <% else %>
                            <li>
                                <%= link_to 'Login', new_admin_session_path %>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EyeCity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="with-top-navbar">
  <%= render 'layouts/navbar' %>
  <div class="alert-msgs text-center">
    <%= render 'layouts/alerts' %>
  </div>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>